# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxPractice
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa'

  # RxSwift Community Projects
  pod 'NSObject+Rx'
  pod 'Action'
  pod 'RxDataSources'
  pod 'RxCoreData


end
